# Generated by Django 4.1.7 on 2023-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_order', models.PositiveIntegerField()),
                ('question_response_type', models.CharField(choices=[('number', 'number'), ('text', 'text'), ('boolean', 'boolean')], max_length=10)),
            ],
        ),
    ]
